FROM mcr.microsoft.com/devcontainers/python:3.14

# Install image processing prerequisites
RUN apt-get update
RUN apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
